version: '3.8'

services:
  django:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      DB_NAME: database-1
      DB_USER: admin
      DB_PASSWORD: Qpwoeiruty11
      DB_HOST: db  # This points to the MySQL service (container name)
      DB_PORT: 3306

  react:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  db:
    image: mysql:8.0  # Use MySQL instead of PostgreSQL
    environment:
      MYSQL_ROOT_PASSWORD: Qpwoeiruty11  # MySQL root password
      MYSQL_DATABASE: database-1  # The database name
      MYSQL_USER: admin  # The database user
      MYSQL_PASSWORD: Qpwoeiruty11  # The password for the database user
    ports:
      - "3306:3306"  # Expose MySQL default port
