# Generated by Django 5.1.4 on 2024-12-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_rename_uploaded_at_resume_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
