# Generated by Django 5.1.4 on 2024-12-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
