# Base image
FROM node:18

# Set working directory
WORKDIR /app/jobent_frontend 

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy source files and build
COPY . .
RUN npm run build

# Use a lightweight web server
RUN npm install -g serve
CMD ["serve", "-s", "build"]

# Expose port
EXPOSE 3000
