# Generated by Django 5.1.4 on 2024-12-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='premium_tokens',
            field=models.IntegerField(default=100),
        ),
    ]
