# Generated by Django 5.1.4 on 2024-12-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usercredentials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='premium_tokens',
            new_name='tokens',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UserCredentials',
        ),
    ]
