# Generated by Django 5.1.4 on 2024-12-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_premium_tokens_userprofile_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('premium', 'Premium')], default='normal', max_length=10),
        ),
    ]
